In [3]:
import sys # Python package for system-specific parameters and functions
from test_segmentation import parse_args, set_random_seed, train_with_config, get_config 
from utils.extract_mp_pose import extract_keypoints # Extract keypoints from images using MediaPipe Pose (sim)

ModuleNotFoundError: No module named 'numpy'

In [ ]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [ ]:
return_dict = extract_keypoints(vidf="test_videos/tedtalk.webm", save_video=True) # Change this to the desired video file path

OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
I0000 00:00:1749840711.937480 16526762 gl_context.cc:369] GL version: 2.1 (2.1 Metal - 88.1), renderer: Apple M3 Pro


Video resolution: 1280.0x720.0, FPS: 25.0
Number of frames in the video: 22056


Processing frames:   0%|          | 0/22056 [00:00<?, ?frame/s]W0000 00:00:1749840712.009590 16529573 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1749840712.020109 16529575 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1749840712.021219 16529581 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1749840712.021276 16529575 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1749840712.021287 16529573 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
W0000 00:00:1749840712

In [ ]:
return_dict['output_path']

'test_videos/tedtalk.npy'

In [ ]:

# pretend the notebook “argv” is your list
sys.argv = ["run_segmentation_test.py"] + [
    "--config",  "config/segmentation/CABB_segment_basic_test.yaml",  # add if you need it
    "--poses-path", return_dict['output_path'],
    "--phase",  "test",
    "--seed",   "42",
    "--devices", "0"
]

opts = parse_args()          # now reads from our fake sys.argv
set_random_seed(opts.seed)
args = get_config(opts.config)

print(f"=== Testing with poses in {opts.poses_path} ===")
segmentation_results = train_with_config(args, opts)


Seed set to 42


=== Testing with poses in test_videos/tedtalk.npy ===
{'train_2d': True, 'has_3d': False, 'no_eval': True, 'finetune': False, 'partial_train': None, 'phase': 'test', 'apply_skeleton_augmentations': True, 'epochs': 200, 'checkpoint_frequency': 30, 'batch_size': 96, 'dropout': 0.1, 'learning_rate': 0.0003, 'weight_decay': 0.01, 'lr_decay': 0.99, 'pretrain_3d_curriculum': 30, 'maxlen': 120, 'dim_feat': 128, 'mlp_ratio': 2, 'depth': 4, 'dim_rep': 256, 'hidden_dim': 256, 'num_heads': 8, 'att_fuse': True, 'pretrained': '', 'model_args': {'modalities': ['skeleton'], 'fusion': 'unimodal', 'feat_dim': 128, 'w2v2_type': 'multilingual', 'skeleton_backbone': 'jointsformer', 'hidden_dim': 256, 'attentive_pooling': True, 'attentive_pooling_skeleton': True, 'bertje_dim': 768, 'freeze_bertje': True, 'cross_modal': False, 'one_branch_cross_modal': False, 'multimodal_embeddings_dim': 1024, 'apply_cnn': False, 'maxlen': 120}, 'modalities': ['skeleton'], 'loss_type': ['cross_entropy'], 'use_contrastive': 

Preparing segmentation sequences...: 100%|██████████| 1/1 [00:00<00:00, 15827.56it/s]
GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/opt/anaconda3/envs/whisperx/lib/python3.10/site-packages/pytorch_lightning/trainer/setup.py:177: GPU available but not used. You can set it by doing `Trainer(accelerator='gpu')`.
Restoring states from the checkpoint path at CABB_Segmentation/fold_1/checkpoints/fold_1/last.ckpt
/opt/anaconda3/envs/whisperx/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:362: The dirpath has changed from '/data/clusterfs/mld/users/esagha/Projects/medal_workshop_on_multimodal_interaction/Gesture_Segmentation_Toturial/Code/CABB_Segmentation/fold_1/checkpoints/CABB-segmentation-20250530_195652_fold_1' to '/Users/esagha/Projects/medal_workshop_on_multimodal_interaction/Gesture_Segmentation_Toturial/Code/CABB_Segmentation/fold_1/checkpoints/CABB-segmentation-20250613_205247_fold_1'

[0 1 3 4 5 6 7 9] [2 8]
Starting Fold 1
INFO: Trainable parameter count: 3345161


/opt/anaconda3/envs/whisperx/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'test_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.


Testing DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s]


/opt/anaconda3/envs/whisperx/lib/python3.10/site-packages/pytorch_lightning/utilities/data.py:79: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 10. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.


┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│  test/segmentation_loss   │    0.05076472833752632    │
└───────────────────────────┴───────────────────────────┘

GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Restoring states from the checkpoint path at CABB_Segmentation/fold_2/checkpoints/fold_2/last.ckpt
/opt/anaconda3/envs/whisperx/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:362: The dirpath has changed from '/data/clusterfs/mld/users/esagha/Projects/medal_workshop_on_multimodal_interaction/Gesture_Segmentation_Toturial/Code/CABB_Segmentation/fold_2/checkpoints/CABB-segmentation-20250530_195652_fold_2' to '/Users/esagha/Projects/medal_workshop_on_multimodal_interaction/Gesture_Segmentation_Toturial/Code/CABB_Segmentation/fold_2/checkpoints/CABB-segmentation-20250613_205247_fold_2', therefore `best_model_score`, `kth_best_model_path`, `kth_value`, `last_model_path` and `best_k_models` won't be reloaded. Only `best_model_path` will be reloaded.
Loaded model weights from the checkpoint at CABB_Segmentation/fold_2/checkpoints/fold_2/last.ckpt


[0 1 2 3 5 6 7 8] [4 9]
Starting Fold 2
INFO: Trainable parameter count: 3345161
Testing DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  1.64it/s]


┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│  test/segmentation_loss   │   0.041764672845602036    │
└───────────────────────────┴───────────────────────────┘

GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Restoring states from the checkpoint path at CABB_Segmentation/fold_3/checkpoints/fold_3/last.ckpt
/opt/anaconda3/envs/whisperx/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:362: The dirpath has changed from '/data/clusterfs/mld/users/esagha/Projects/medal_workshop_on_multimodal_interaction/Gesture_Segmentation_Toturial/Code/CABB_Segmentation/fold_3/checkpoints/CABB-segmentation-20250530_195652_fold_3' to '/Users/esagha/Projects/medal_workshop_on_multimodal_interaction/Gesture_Segmentation_Toturial/Code/CABB_Segmentation/fold_3/checkpoints/CABB-segmentation-20250613_205247_fold_3', therefore `best_model_score`, `kth_best_model_path`, `kth_value`, `last_model_path` and `best_k_models` won't be reloaded. Only `best_model_path` will be reloaded.
Loaded model weights from the checkpoint at CABB_Segmentation/fold_3/checkpoints/fold_3/last.ckpt


[0 2 3 4 5 7 8 9] [1 6]
Starting Fold 3
INFO: Trainable parameter count: 3345161
Testing DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  1.65it/s]


┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│  test/segmentation_loss   │    0.04847728833556175    │
└───────────────────────────┴───────────────────────────┘

GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Restoring states from the checkpoint path at CABB_Segmentation/fold_4/checkpoints/fold_4/last.ckpt
/opt/anaconda3/envs/whisperx/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:362: The dirpath has changed from '/data/clusterfs/mld/users/esagha/Projects/medal_workshop_on_multimodal_interaction/Gesture_Segmentation_Toturial/Code/CABB_Segmentation/fold_4/checkpoints/CABB-segmentation-20250530_195652_fold_4' to '/Users/esagha/Projects/medal_workshop_on_multimodal_interaction/Gesture_Segmentation_Toturial/Code/CABB_Segmentation/fold_4/checkpoints/CABB-segmentation-20250613_205247_fold_4', therefore `best_model_score`, `kth_best_model_path`, `kth_value`, `last_model_path` and `best_k_models` won't be reloaded. Only `best_model_path` will be reloaded.
Loaded model weights from the checkpoint at CABB_Segmentation/fold_4/checkpoints/fold_4/last.ckpt


[0 1 2 4 5 6 8 9] [3 7]
Starting Fold 4
INFO: Trainable parameter count: 3345161
Testing DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s]


┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│  test/segmentation_loss   │   0.044202398508787155    │
└───────────────────────────┴───────────────────────────┘

GPU available: True (mps), used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
Restoring states from the checkpoint path at CABB_Segmentation/fold_5/checkpoints/fold_5/last.ckpt
/opt/anaconda3/envs/whisperx/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:362: The dirpath has changed from '/data/clusterfs/mld/users/esagha/Projects/medal_workshop_on_multimodal_interaction/Gesture_Segmentation_Toturial/Code/CABB_Segmentation/fold_5/checkpoints/CABB-segmentation-20250530_195652_fold_5' to '/Users/esagha/Projects/medal_workshop_on_multimodal_interaction/Gesture_Segmentation_Toturial/Code/CABB_Segmentation/fold_5/checkpoints/CABB-segmentation-20250613_205247_fold_5', therefore `best_model_score`, `kth_best_model_path`, `kth_value`, `last_model_path` and `best_k_models` won't be reloaded. Only `best_model_path` will be reloaded.
Loaded model weights from the checkpoint at CABB_Segmentation/fold_5/checkpoints/fold_5/last.ckpt


[1 2 3 4 6 7 8 9] [0 5]
Starting Fold 5
INFO: Trainable parameter count: 3345161
Testing DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  1.62it/s]


┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│  test/segmentation_loss   │    0.03944703936576843    │
└───────────────────────────┴───────────────────────────┘

Saving results to CABB_Segmentation/fold_5/test_results.pkl


In [ ]:
file_path=return_dict['output_path']

In [ ]:
from Gesture_Segmentation_to_ELAN import get_elan_files
# copy segmentation_results 
segmentation_results_copy = segmentation_results.copy()
get_elan_files(segmentation_results_copy, fps=return_dict['samplerate'], model='skeleton', threshold=0.55, file_path=return_dict['output_path'], video_output_path=return_dict['video_output_path'])


100%|██████████| 5/5 [00:00<00:00, 207.30it/s]


Fold 0 - Number of samples: 10, Number of sequences: 120
Fold 1 - Number of samples: 10, Number of sequences: 120
Fold 2 - Number of samples: 10, Number of sequences: 120
Fold 3 - Number of samples: 10, Number of sequences: 120
Fold 4 - Number of samples: 10, Number of sequences: 120


100%|██████████| 1/1 [00:00<00:00, 147.73it/s]

Pair: 77
Speaker: B
